### ISSUE TITLE
More customization per paginated page

### ISSUE THREAD

**Issue by sarcasmloading** [foxbot/Discord.Addons.Interactive#2]
Similar to how it was done in `Discord.Addons.Paginator`, it would be nice to be able to add fields to an individual page - instead of using `object` in the pages list, it would have be a custom class.

Other suggestions would include being able to add an image/thumbnail per page, as well as setting other options, like changing the title, setting the color and changing the author per page.

**Comment by rishav394** [comment]
@sarcasmloading Why close the issue? Did you find a solution?
