### ISSUE TITLE
Update Nuget

### ISSUE THREAD

**Issue by martindevans** [foxbot/Discord.Addons.Interactive#20]
The [nuget package](https://www.nuget.org/packages/Discord.Addons.Interactive/1.0.1) for this project appears to be _three years_ out of date! Could you push a newer version? Thanks :)

**Comment by daviesro** [comment]
Seems there was an update 10 hours ago: https://www.nuget.org/packages/Discord.Addons.Interactive

**Comment by martindevans** [comment]
Thanks 👍
