### ISSUE TITLE
The name 'PagedReplyAsync' does not exist in the current context.

### ISSUE THREAD

**Issue by Esherymack** [foxbot/Discord.Addons.Interactive#21]
As stated in title. Library was added via NuGet today; attempting to use the pagination module does not seem to be possible due to inability to access the PagedReplyAsync method. 

```cs
string[] files = Directory.GetFiles(@".\data", "*");
files = files.Select(Path.GetFileName).ToArray();


/* Attempting to test pagination */
var pages = new[] { "Page 1", "Page 2" };


await PagedReplyAsync(pages); // Error comes in here.
```

The project is using .NET Core 3.1 and hasn't had any problems with Discord.NET. I tried cloning this and manually adding it to the project as a dependency with no results. I also tried rebuilding the .dll myself.

The sample project will, however, load and build. I'm confused.

**Comment by bsquidwrd** [comment]
You'll have to setup their MyNuget Repo for NuGet as outlined here: https://discord.foxbot.me/stable/guides/getting_started/installing.html?tabs=vs-install%2Ccore2-1

Then make sure your command is implementing (I think that's the right term) the `InteractiveBase` instead of `ModuleBase` so like this:
```csharp
using Discord.Addons.Interactive;
...
public class MyCommandModule : InteractiveBase<SocketCommandContext>
```

**Comment by Esherymack** [comment]
Okay. I was unaware of the need to implement it as `InteractiveBase` and was trying to use it in a `ModuleBase` class. The name now exists - thank you!
