### ISSUE TITLE
Embed Pages

### ISSUE THREAD

**Issue by Venipa** [foxbot/Discord.Addons.Interactive#22]
is it possible to use embed and normal strings as pages.

as an example:
pages = [Embed, string, Embed, Embed]

**Comment by MrKev312** [comment]
Just added this into my fork if you still need this: https://github.com/MrKev312/Discord.Addons.Interactive

**Comment by Venipa** [comment]
> Just added this into my fork if you still need this: https://github.com/MrKev312/Discord.Addons.Interactive

ah forgot to mention that i've already fixed this issue myself in my fork:
https://github.com/Venipa/Discord.Addons.Interactive/commit/abf050b5b40bab13668e71cfe1dd647573a105f2
