### ISSUE TITLE
Interactivity not working

### ISSUE THREAD

**Issue by DriesMagnus** [foxbot/Discord.Addons.Interactive#23]
As I could not find a support Discord Server or anything else, I thought I'd ask it here.

As stated, adding the `using` statement (`using Discord.Addons.Interactive;`) is not enough, I have to let the class inherit from `InteractiveBase`. (Otherwise it does not know AT ALL what `NextMessageAsync()` is/means.)
The only issue I'm facing now is that I inherit `ModuleBase<SocketCommandContext>` to actually trigger my commands when someone types them in a channel.
I have tried to work only with inheriting `InteractiveBase` but then my bot does not respond anymore to any command in that class, not even the command I am using the interactivity in.

Am I missing something here? It's 2AM here for me so that is very likely.

Kind regards.

**Comment by OoLunar** [comment]
> As I could not find a support Discord Server or anything else, I thought I'd ask it here.

discord.gg/discord-api

> The only issue I'm facing now is that I inherit ModuleBase<SocketCommandContext> to actually trigger my commands when someone types them in a channel.

So you want to execute a command before the user sends a message? It'd be a lot easier to see what you're trying to do with some code examples... Go ahead and ask again on DAPI if you haven't already. Please close the issue if you already have found a solution.
