### ISSUE TITLE
InteractiveBase seems to not work at all

### ISSUE THREAD

**Issue by dataccountzXJ9** [foxbot/Discord.Addons.Interactive#3]
Not any command fires after debugging.

[Added to service provider, client is not null](https://github.com/happydude82/Lynx/blob/master/Lynx/Core/Core.cs#L44)
[Link to Module](https://github.com/happydude82/Lynx/blob/master/Lynx/Modules/CustomReactions.cs)

**Comment by TurboLOL** [comment]
What command context are you passing in ExecuteAsync(), cause for interactive base to work it needs SocketCommandContext

**Comment by dataccountzXJ9** [comment]
Yeah found out im using the wrong context. Ported it to my own. Thanks!
