### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by DenVot** [foxbot/Discord.Addons.Interactive#33]
Hello.

I can't understand. Why I catch this exception?

Part of my code:
```csharp
                //Before I got List<string> of commands
                try
                {
                    await PagedReplyAsync(pager: new PaginatedMessage
                    {
                        Title = "Instruction",
                        Pages = pages,
                        Color = ColorProvider.GetColorForCurrentGuild(serGuild),
                        Options = new PaginatedAppearanceOptions
                        {
                            Jump = null,
                            Info = null,
                            Stop = null
                        }
                    });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
```

![image](https://user-images.githubusercontent.com/69825463/111368375-da4b6780-86a6-11eb-9532-401b0f6ddd86.png)

**Comment by TheStachelfisch** [comment]
Discord.Addons.Interactive is not compiled for the newest Discord.Net version. 

You have to manually update the Discord.Net packages that Discord.Addons.Interactive uses and then recompile again.

**Comment by JoyfulReaper** [comment]
> Discord.Addons.Interactive is not compiled for the newest Discord.Net version.
> 
> You have to manually update the Discord.Net packages that Discord.Addons.Interactive uses and then recompile again.

Could you explain how I can do this? Edit: I was able to download the source from github, build it as nuget package, add a local nuget source and use that with the updated dependency versions, hope that helps someone else while waiting for pull request #34  to be merged.
